[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
meval = "0.2.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"